### PR TITLE
Use modules in go example instead of dep

### PR DESCRIPTION
**Pull request by hkolvenbach**
I tried to follow the go + aws example (see issue #647) and hit a few roadblocks. This PR allows to compile the example again, although I don't think the package structure is very "go-like".

Signed-off-by: Hanno Kolvenbach <hannokolvenbach@gmx.de>

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you. I'm not familiar with go, so I can't judge the "go-like" structure and I can't help unfortunately.

I would still say that a working example is better than a broken one, so I would merge that for now (to improve things immediately). @medikoo WDYT?

**Comment by medikoo** [comment]
@mnapoli I'm totally +1. I also, unfortunately, do not have that much experience in Go, so I guess we have to trust the community

**Review by mnapoli — APPROVED** [review]
👍  then

**Comment by hkolvenbach** [comment]
I think no matter of the structure, it will still help go developers get started. I assume Go developers using the example would reorganize the go code anyway, as soon as it gets a bit more involved. The important part is to see how it interacts with serverless and the Makefile

**Comment by mnapoli** [comment]
Merging, per discussion.

**Pull request merged**
