### PR TITLE
Add adoptable-pet-bot to community examples

### PR DESCRIPTION
**Pull request by lynnaloo**

### CODE REVIEW

**Comment by lynnaloo** [comment]
The README.md is updated, but it's still failing travis-ci 😕

**Comment by christophgysin** [comment]
Known issue, fixed in #116

**Comment by lynnaloo** [comment]
@christophgysin nice work!

**Comment by christophgysin** [comment]
#116 has now been merged, if you rebase on top of master it should now pass the travis check.

**Comment by lynnaloo** [comment]
@christophgysin 🎉

**Pull request merged**
