### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by darrenhgc**
**This has not been tested with an active Twilio account.**

This PR is in reply to issue [#158](https://github.com/serverless/examples/issues/158) and is meant to drive discussion around writing tests.

### CODE REVIEW

**Comment by kbariotis** [comment]
This looks absolutely great. Couldnt run it though, im currently on a mobile.

**Comment by darrenhgc** [comment]
I've tested this with an active twilio account and is okay to merge.

**Comment by luebken** [comment]
Great stuff! Very helpful.

Here are some minor thoughts / ideas. Note: I’m not a NodesJS / serverless expert here. So take this with a grain of salt. 

* I’m not sure if tests are _always_ needed. So while I think this great for a lot of people I also guess some would appreciate the raw non-tested example. So I would advocate for two versions: one without tests and a “tested” version.

* I’m not a eslint / mocha expert but if we advocate for the canonical way of describing mocha tests they shouldn’t need exceptions like `+describe('Messenger', () => { // eslint-disable-line`
Not sure what the proper resolution is. I’ve added `mocha` to .eslintrc.json https://github.com/serverless/examples/pull/162/files#diff-df39304d828831c44a2b9f38cd45289c

**Comment by kbariotis** [comment]
> I’m not sure if tests are always needed. So while I think this great for a lot of people I also guess some would appreciate the raw non-tested example. So I would advocate for two versions: one without tests and a “tested” version.

Based on my experience, I can assure you that tests are always needed. Also, one can just browse the source folder and leave the tests or run the examples without even care that tests are also there.Two separate version is just duplication, which is not good at all.

**Pull request merged**
