### PR TITLE
Adds FaunaDB python example

### PR DESCRIPTION
**Pull request by marrony**
This is an example based on `aws-python-rest-api-with-dynamodb` that uses [FaunaDB](https://fauna.com) as a data storage.

### CODE REVIEW

**Comment by nikgraf** [comment]
@marrony awesome, thx 👏

Can you create another PR where you update the Readme? You need to provide a secret: `YOUR-SECRET-HERE`. This should be documented, otherwise people might get confused …

**Comment by marrony** [comment]
I had documented this in the last line of the [Readme](https://github.com/serverless/examples/pull/104/files#diff-cccec286ef19b73b88823c4630d1c54dR146). Do you believe I need to clarify with some example?

**Comment by nikgraf** [comment]
Ahh, I missed that one.

The readmes follow all the same pattern: In the beginning a setup section how to get the whole example up & running followed by how to use it. I would suggest we move it just to the setup part and then it's done 😄

**Comment by jchris** [comment]
@marrony as you are updating it, I've modified the last line of the readme to use the signup URL. Maybe this line can go near the top of the readme:

```
Visit https://fauna.com/serverless-cloud-sign-up to obtain a `FAUNADB_SECRET` to use in `serverless.yml`.
```

**Pull request merged**
