### PR TITLE
add node recursive invocation example

### PR DESCRIPTION
**Pull request by DavidWells**
Add recursive invocation example and readme

### CODE REVIEW

**Comment by nikgraf** [comment]
@DavidWells finally got around to review this. As you mentioned this can be dangerous if a newbie fiddles with the code and creates infinite running Lambdas. It can become quite expansive quickly.

I was looking for a use-case: constantly fetching and processing new input from another service as fast as the processing can happen, but not running the processing task in parallel.

What do you think if you or me re-write it to this to encourage a best practice:

- We use a dynamoDB table as registry to store the running recursive cycles.

- If the Lambda is triggered it checks if an entry in the table exists. In case not it creates one (it's a new recursive cycle) and triggers the next Lambda (using SNS). It also checks for other running cycles and mark them to stop.

- If the Lambda finds it's entry and it's not marked to be stopped it just continues to run. If it is marked as stopped it will remove the entry from the the table and don't trigger another Lambda.

- In addition we add a Lambda which marks all Lambdas to be stopped after 5 minutes (just for safety).

By using SNS and the registry this should be fault prove. It's still a very delicate matter to fiddle and deploy this example. Should we add it at all?

**Comment by DavidWells** [comment]
Yeah. Maybe https://github.com/pmuens/serverless-lambda-chaining/blob/master/handler.js would be better.

Or a super simple example of how you can call other lambda functions from a lambda

**Comment by AndrewFarley** [comment]
I was just looking at PRs, and amusingly mine is similarly related to this one.  I just submitted a PR that adds an example that uses a chained Lambda approach for a specific purpose.  To respond to what @DavidWells mentioned, there is a distinct use-case for using a SNS as mentioned, but there's also a distinct use case to NOT use it.  My PR has a very clear and necessary use case to not use it.  https://github.com/serverless/examples/pull/40

**Comment by nikgraf** [comment]
@AndrewFarley why can't you use SNS in your case?

Holding back on the PR was mostly, because I'm worried a beginner could screw up and be very frustrated by finding out they paid a lot of money due that.

**Comment by AndrewFarley** [comment]
@nikgraf My case could be re-engineered to work via an SNS, and surely every case probably could but in my case, if you looked at my project you would see the reasons I do not use SNS is...

1. If I used a SNS, I would still need two Lambdas, so I would be paying MORE money ALSO calling a SNS (minimal cost, but true at higher volumes) so for my project your assumption is incorrect as I have one in-vpc Lambda, and one out-of-VPC lambda.
1. It adds another dependency to the stack of services that must be functional for this software to work, and generally the best architecture is the simplest path to achieve the goal without sacrificing anything.
1. Since the output of one Lambda is used in directly used in another Lambda, and there is a one-to-one relationship of one lambda calling another, and since there is _never_ an overlap, a "buffer" or "queue" that SNS adds is unnecessary and burdensome.
1. In my case, if I used SNS, and leveraged its "retry" functionality (basically, one of the best reasons to use SNS) if the queue got backed up at all and retried the request a bit later, the data it retrieved would not be relevant/proper and would be all bunched up when inserted into CloudWatch.  I intentionally, and purposefully DO NOT WANT a queue or a retry mechanism.  There can be slight gaps in the CloudWatch metrics, and that's just fine.  But if I had a queue full of attempts to query a database that backed up because lets say I was running migrations or did an upgrade on RDS or something.  If that queue suddenly got unleashed on a database, it could potentially overload a database (depending on the queries) and the results of those queries would be nearly useless in CloudWatch as they would all be inserted against the same timestamp (unless I re-engineered my software to work based on the timestamp of when the queue item was first initialized, which would add an INSANE amount of complexity)

All I'm trying to point out to you and anyone reading is that you shouldn't always be leaning on SNS.  I use it plenty, tons.  But, please understand the technology and complexity debt incurred by introducing all these external dependencies (as you mentioned above, SNS or DynamoDB). There are distinct use-cases in which you should not use SNS (or, could still use it but completely disabling its retry/backoff mechanisms, but then begs the question again as to why use it). Anyway, if you'd like to discuss more finer points, feel free to reach out to me privately.

**Pull request merged**
