### PR TITLE
Master

### PR DESCRIPTION
**Pull request by kuashe**
AWS Node MongoDB example

### CODE REVIEW

**Comment by kuashe** [comment]
@DavidWells I'm running "npm run docs" but nothing happens , am I missing something ?

**Comment by christophgysin** [comment]
npm run docs will update the README.md. You will need to add those changes to the PR to pass the travis check.

**Comment by kuashe** [comment]
@christophgysin Nothing happens when i run `npm run docs`

**Comment by kuashe** [comment]
`npm run docs` only works on Unix system it seems like...

**Comment by christophgysin** [comment]
What system does it not work on? Could you open an issue for it?

**Comment by kuashe** [comment]
@christophgysin Windows 10 , as stated above , the CLI returns saying "Docs Updated" but nothing really happens .

**Comment by christophgysin** [comment]
Please open an issue for this. Thanks!

**Comment by DavidWells** [comment]
@kuashe thanks for this example! You rock!

**Pull request merged**
