### PR TITLE
updated auth0 lock version and fixed auth function

### PR DESCRIPTION
**Pull request by assafg**

### CODE REVIEW

**Comment by assafg** [comment]
Anyone maintaining this repo?

**Comment by lis186** [comment]
It works!

**Comment by torntrousers** [comment]
This gets the example working for me, it doesn't work otherwise. Would be good to get this merged.

**Comment by assafg** [comment]
This repo does not seem to be maintained :(

**Comment by eahefnawy** [comment]
Hey @assafg, really sorry for putting this in the backlog for too long 😊 , my bad!

Thanks a lot for your contribution! Merging... 🎉

**Pull request merged**
