### PR TITLE
Dynamodb streams to S3 (backup) example

### PR DESCRIPTION
**Pull request by kaihendry**
I use this at work to have a backup of our DynamoDB tables. It also serves as a handy fallback when the inevitable "dynamodb throughput exceeded" occurs.

### CODE REVIEW

**Comment by kaihendry** [comment]
Don't quite understand the README issue.. is that for me to fix or can you do it please?

**Comment by alexdebrie** [comment]
Hi @kaihendry -- interesting example! Great idea for having a backup of the data for more offline use cases.

For the error, I think you'll need to run `npm run docs` -- look at the `Adding example code` steps in the [Contributing](https://github.com/serverless/examples#contributing) section of the README.

Also, a few other notes:

- Could you add to the README in your example to say what it does and why it's useful? 
- You can use the Serverless Framework to map DynamoDB triggers to Lambda functions (docs [here](https://serverless.com/framework/docs/providers/aws/events/streams/)). Could you add that?

Let me know if you have any questions.

**Comment by kaihendry** [comment]
I tried before with the events stanza and I couldn't figure it out. Ended up manually doing it on the AWS console. So if you could help, I would be grateful.

**Comment by alexdebrie** [comment]
Sure thing, I'll take a look. Can you work on the README?

**Comment by kaihendry** [comment]
Thought I updated the README. Still the check fails... ummm, any ideas?

**Pull request merged**
