### PR TITLE
travis: check if docs have been generated

### PR DESCRIPTION
**Pull request by christophgysin**

### CODE REVIEW

**Comment by christophgysin** [comment]
Please note that the checks that failed above are because currently, the README.md is not up-to-date.

**Comment by nikgraf** [comment]
thanks @christophgysin 🙌

btw we gave you write access to this repository. feel free to merge PRs or add examples. Ideally we still review each other though 😄

**Comment by christophgysin** [comment]
Awesome, thanks!

**Comment by christophgysin** [comment]
> btw we gave you write access to this repository. feel free to merge PRs or add examples. Ideally we still review each other though 😄

@nikgraf I still don't seem to be able to merge PRs in this repo.

There is a strange behavior in `git diff-index` that breaks this check. Should be fixed in #116. That also updates the README, since it is again out of date. Could you merge this?

**Pull request merged**
