### PR TITLE
Rust examples for OpenWhisk and AWS

### PR DESCRIPTION
**Pull request by jonee**

### CODE REVIEW

**Review by eahefnawy — APPROVED** [review]
Thanks for sharing @jonee

**Comment by jonee** [comment]
Sorry can you let me know how that is done? @eahefnawy

**Comment by eahefnawy** [comment]
Just run `npm run docs`. More info here:
https://github.com/serverless/examples#contributing

**Comment by jonee** [comment]
Done thanks! @eahefnawy

**Pull request merged**
