### PR TITLE
add example for full stack application (front end and backend)

### PR DESCRIPTION
**Pull request by trilom**

### CODE REVIEW

**Comment by worldsoup** [comment]
@trilom fix the tests and we can merge

**Comment by trilom** [comment]
looking at this, when running `npm docs run` on my local machine it generates readme.md information, but since the example contains 2 directories with 2 serverless.yml files, when the `npm docs run` command is run it will generate 2 entries for each of those instead of the desired 1 that we want as reflected above.

Not 100% sure, but it seems we can push this through it it should be fine since the tests don't handle the exact case we are deploying at this time.

**Comment by worldsoup** [comment]
@trilom did you test it by running 'serverless install' pointed at the directory on the enterprise repo to see if it works as expected with two yml files? if you've confirmed that it works as expected I'll go ahead and merge

**Comment by trilom** [comment]
@worldsoup Yes - the directory being merged has 2 directories and a readme.  The readme has instructions for how to deploy the two serverless.yml files.  When running `serverless install` on those per the instructions, they build the desired infrastructure.

**Pull request merged**
