### PR TITLE
cleanup gitignore definitions

### PR DESCRIPTION
**Pull request by christophgysin**
Remove duplicate gitignore definitions. Also, the "**/" prefix is the
default behaviour, and can be omitted.

### CODE REVIEW

**Comment by DavidWells** [comment]
I believe the additional `.gitignore` files exist for the install sub-folder https://serverless.com/framework/docs/providers/aws/cli-reference/install#installing-a-service-from-a-directory-in-a-github-url command

**Comment by christophgysin** [comment]
Ah, I see, that makes sense.

In that case, they all should list `.serverless` and all aws-node-*/.gitignore should list `node_modules`. I will change this PR accordingly.

**Comment by christophgysin** [comment]
Pushed an updated commit, adding `.gitignore` files to all examples.

**Comment by nikgraf** [comment]
awesome thanks @christophgysin!

going to look into the other PRs tomorrow

**Pull request merged**
