### PR TITLE
Added my GraphQL example project

### PR DESCRIPTION
**Pull request by boazdejong**
Hoping this will help people to get started building a GraphQL API using the Serverless Framework. This also shows how to use [graphql-tools](https://github.com/apollographql/graphql-tools) and [gql-merge](https://github.com/liamcurry/gql/tree/master/packages/gql-merge) to merge and generate a schema for large projects.

### CODE REVIEW

**Comment by boazdejong** [comment]
Not sure why it is failing because I did run `npm run docs`.

**Comment by christophgysin** [comment]
There was a bug in the check, should be fixed in #116.

**Comment by boazdejong** [comment]
@christophgysin Thanks, I'll wait for it to be merged and then retry.

**Comment by christophgysin** [comment]
#116 has now been merged, if you rebase on top of master it should now pass the travis check.

**Comment by boazdejong** [comment]
I am very new to git, but will figure out how to do that soon. I'm assuming you can't use the 'Rebase and Merge' option from the merge button?

**Comment by christophgysin** [comment]
Rebasing is not needed to merge, but to pass the check. Merging now would bypass the check.

**Pull request merged**
