### PR TITLE
feat: Add aws node typescript warmup community example

### PR DESCRIPTION
**Pull request by Pigius**
I've been away for a long time 😅 @pgrzesik  Time to get back to adding examples but only on the typescript. The first example will be a warmup lambda function, because of the cold start. A simple example in Typescript is how to solve this using the plugin https://github.com/juanjoDiaz/serverless-plugin-warmup

### CODE REVIEW

**Comment by Pigius** [comment]
I've made sth wrong with git.

**Comment by Pigius** [comment]
Resolved

**Review by pgrzesik — COMMENTED** [review]
Thanks a lot @Pigius for the submission 🙌 I have a question about the approach here in general - is there a reason why using warmup plugin is better than using provisioned concurrency?

**Comment by Pigius** [comment]
> Thanks a lot @Pigius for the submission 🙌 I have a question about the approach here in general - is there a reason why using warmup plugin is better than using provisioned concurrency?
Sure @pgrzesik. Costs mostly, the duration cost is much less than the Lambda ping approach, but you need to consider the provisioned capacity cost as well, which could be costly (https://enlear.academy/how-to-avoid-lambda-cold-starts-917437434c95). 

And in general, I also wanted to present another way how this problem can be solved.

**Comment by pgrzesik** [comment]
Thanks for clarification @Pigius 💯 

@mnapoli What do you think about this type of example here? Should we consider it or rather suggest to add as a community example?

**Comment by mnapoli** [comment]
Thanks for the ping. I actually want to bring the point internally that we might want to consider not adding new community examples in this repository.

Examples in this repository are marked as "provided by serverless", which is confusing to users because we actually don't maintain them or write them.

Community examples hosted in 3rd party organizations/user accounts is actually much more explicit on what the example is: it's an example from someone in the community.

So I would suggest that from now on, we don't add new examples here, we only accept references in `examples.json`, what do you think?

**Comment by pgrzesik** [comment]
I think that could be the best choice here, given our future plans for the `examples` repository in general

**Comment by Pigius** [comment]
@pgrzesik added as a community example.

**Review by pgrzesik — APPROVED** [review]
Thanks a lot @Pigius 🙇

**Pull request merged**
