### PR TITLE
change from put to update

### PR DESCRIPTION
**Pull request by velulev**
put is not the best option to explain DynamoDB Item update. In the earlier example, the attributes that are not updated, like createdAt will be lost, as put writes the entire new document (and the current example does not include the createdAt attribute), resulting in the attributes not supplied in the put being lost. Also updated the validation condition from AND (&&) to OR (||)

### CODE REVIEW

**Comment by nikgraf** [comment]
ohhh, you are right. Didn't know aobut that. Seems like you reverted you changes. Wanna do them again and fix linting so I can merge it?

**Comment by velulev** [comment]
Hi Nik, Build #226 (4f1081d) failed, I then made the whitespace character corrections and Build #228 (5024a36) passed. Please let me know if you still cannot access Build #228 (5024a36). I am not a Git Expert, so, let me know if I am missing something. Thanks.

**Comment by velulev** [comment]
Hi Nik, Please check if this has the changes, and you are happy with them. Thanks.

**Comment by nikgraf** [comment]
@velulev looks good, thanks helping out here 🙌

**Pull request merged**
