### PR TITLE
add auth0 protected API example

### PR DESCRIPTION
**Pull request by DavidWells**
Protect API routes with auth0 json web tokens.

Open to suggestions on the name of this example. cc @nikgraf @ac360 

The folder name is currently `aws-auth0-api-gateway`

### CODE REVIEW

**Comment by nikgraf** [comment]
@DavidWells nice one! This is super useful. Over the weekend I learned a lot about providing secure credentials to AWS Lambda. I will work out an example and then we can apply this here as well so people by default use best practices 🙂

**Comment by DavidWells** [comment]
Are you talking about using KMS for the auth0 secret key?

**Comment by DavidWells** [comment]
-> "Our testing has shown that the latency to decrypt a secret using a KMS CMK is often around 2 seconds" https://github.com/serverless/serverless/issues/472#issuecomment-170460178

Ouchie

**Comment by nielslanting** [comment]
I was wondering why aren't you doing the the verification in a custom authorizer?

**Comment by DavidWells** [comment]
@nielslanting Thats a good idea. Something like this? https://github.com/laardee/serverless-authentication-boilerplate/blob/master/test-token/serverless.yml#L18-L22

**Comment by nielslanting** [comment]
@DavidWells Yes something like that. You don't have to specify the authorizer by it's ARN if the function is in the same service. I created a PR which uses the authorizer. [https://github.com/serverless/examples/pull/23](url)

**Comment by DavidWells** [comment]
@nielslanting I deployed the changed but it looks like i'm getting a CORS issue from the demo http://auth0-serverless-protected-routes-demo.surge.sh/

```
Fetch API cannot load https://bxr94xtq93.execute-api.us-east-1.amazonaws.com/dev/api/private. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://auth0-serverless-protected-routes-demo.surge.sh' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Do the CORs setting need to change for the custom authorizer? https://github.com/serverless/examples/blob/auth0-example/aws-auth0-api-gateway/serverless.yml#L30-L34

**Comment by DavidWells** [comment]
@nielslanting Looks like there is a CORS issue with these updates. See: http://auth0-serverless-protected-routes-demo.surge.sh/

```
Fetch API cannot load https://bxr94xtq93.execute-api.us-east-1.amazonaws.com/dev/api/private. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://auth0-serverless-protected-routes-demo.surge.sh' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Do the headers need to change for the custom authorizer to work? https://github.com/serverless/examples/blob/auth0-example/aws-auth0-api-gateway/serverless.yml#L30-L34

**Comment by DavidWells** [comment]
@nielslanting more specifically, the logged in protected route does work! 🎉 However if not logged in, the CORS error returns. See: http://www.screencast.com/t/gSIgj7SDB

Any ideas on how to solve this. Otherwise I might need to handle the error client side =)

Many many thanks on your help! You rock

**Comment by nielslanting** [comment]
@DavidWells To be honest I have no idea how to solve this. I found the following [https://forums.aws.amazon.com/thread.jspa?messageID=710770&#710770](url). 

> Apologies but we still do not have an update on when a fix would be available and there is still currently no work around for this issue. I appreciate that this is not a satisfying response given the time that this issue has been open, but we are aware of the pain this issue causes and hope to have something to address it soon. ~ BobK@AWS - Nov 15, 2016 5:50 PM

**Pull request merged**
