### PR TITLE
feat: Update `.net` examples to .NET 6

### PR DESCRIPTION
**Pull request by slang25**
Updates the C# and F# AWS Lambda legacy templates to use the .NET 6 managed Lambda runtime.

### CODE REVIEW

**Comment by slang25** [comment]
Hey @pgrzesik, so .NET Core was rebranded after .NET Core 3.1 to just .NET 5, then .NET 6.

.NET 6 supports C# 10, which is backwards compatible with previous C# versions. You have prompted me though to modernize the C# style 👍

**Comment by slang25** [comment]
cc @martincostello

**Review by martincostello — APPROVED** [review]
Nice.

**Review by pgrzesik — APPROVED** [review]
Thank you @slang25 🙇

**Pull request merged**
