### PR TITLE
Add new example

### PR DESCRIPTION
**Pull request by calvintychan**
Include serverless-html-pdf example.

### CODE REVIEW

**Comment by DavidWells** [comment]
@calvintychan this is awesome! Thanks for the PR

Would you be interested in potentially sharing this on our blog? https://serverless.com/blog https://github.com/serverless/blog

**Comment by calvintychan** [comment]
Hi @DavidWells – Absolutely. Happy to contribute.

**Comment by Stefmonge** [comment]
Hi @calvintychan! Excited to feature your post on the Serverless blog. You can submit your post in a PR at https://github.com/serverless/blog. We can schedule it as soon as next Wednesday, March 8 if it's ready. Otherwise we can look to the following week. Let me know what you think.

Feel free to reach me directly at stefanie@serverless.com if you have any questions.

**Comment by calvintychan** [comment]
Hi @Stefmonge – thank you! I will keep you posted with the progress.

**Comment by Stefmonge** [comment]
Hey @calvintychan! Scheduling April posts right now. I could put this on the calendar mid-month if that works for you. Let me know!

**Pull request merged**
