### PR TITLE
Fix response ordering in https://github.com/serverless/examples/pull/81

### PR DESCRIPTION
**Pull request by kaihendry**
Sorry for the earlier error on #81

### CODE REVIEW

**Comment by christophgysin** [comment]
Fixed in #124

**Comment by kaihendry** [comment]
Thanks, the next thing that bothers me, is if the fetch fails, the callback returns `{"errorMessage":"[object Object]"}`

I'm sure sure if the Promise error or the Lambda callback is to blame.

**Comment by christophgysin** [comment]
@kaihendry How about #126?

**Comment by kaihendry** [comment]
Looks good. How do I quickly pull in christophgysin:improve-error-message on my cli to test I wonder??

Btw this is sage advice from a better JS programmer than I @timoxley regarding the callback return:

in the first example with the .then(v => callback(null, v)).catch(callback), control goes:
1. work
2. callback
3. work (bad: control should never be passed back to the async function after it calls callback)
4. callback (bad: callbacks should never be executed twice)
5. crash

while in the second example with .then(v => callback(null, v), callback), control goes:
1. work
2. callback
3. crash

in the second case, control flows correctly and the callback is run only once.

**Comment by christophgysin** [comment]
> How do I quickly pull in christophgysin:improve-error-message on my cli to test

```
git pull https://github.com/christophgysin/examples improve-error-message
```

**Comment by christophgysin** [comment]
@kaihendry As for the advice, I'm not entirely following what you are referring to. Could you comment directly on the relevant lines in the code/PR you are referring to?

**Comment by kaihendry** [comment]
LGTM https://s.natalian.org/2017-03-31/1490947749_2548x1380.png

**Pull request closed without merging**
