### PR TITLE
Updating node verson

### PR DESCRIPTION
**Pull request by ColtonHerrodWork**
Updating the node version for the example TODO application since 6.x is no longer supported in Lambda.

### CODE REVIEW

**Comment by christophgysin** [comment]
There are a few more examples that still use nodejs6.10, could you update those too?

https://github.com/serverless/examples/search?q=%22runtime%3A+nodejs6.10%22

**Comment by ColtonHerrodWork** [comment]
Updated the rest of them, should be good to go now.

**Comment by ColtonHerrodWork** [comment]
Updated existing examples to nodejs12.x to leverage latest supported runtime.

**Comment by eahefnawy** [comment]
@ColtonHerrodWork I know this review is long overdue. I'm sorry about that. I'd like to merge this right away! Could you just fix the conflicts? 😊

**Comment by fvant** [comment]
@ColtonHerrodWork   you have a possibility to resolve that merge conflict ? or would you like a hand ?

**Comment by preshetin** [comment]
@fvant I think it was already resolved in https://github.com/serverless/examples/pull/486

So I think this should be closed

**Comment by fvant** [comment]
> @fvant I think it was already resolved in #486
> 
> So I think this PR should be closed

i checked out aws-node-env-variables today and it still had node8.10, triggering me to checkout the PR/issues
#486 only has 1 file...

**Comment by preshetin** [comment]
@fvant I see. 

It seems there is no activity. So if you decide to create a PR, you may ping me to make a code review

**Comment by fvant** [comment]
@preshetin created #501 with resolved merge conflict

**Pull request merged**
