### PR TITLE
Add JWKS token authentication (for Auth0 and AWS Cognito)

### PR DESCRIPTION
**Pull request by shahzeb1**
Fixes issue #200 by adding a new authenticator node.js example which works with [JWKS](https://auth0.com/docs/jwks) tokens.
This authenticator can be used either with Auth0 or AWS Cognito (tutorial in README.md).

### CODE REVIEW

**Comment by shahzeb1** [comment]
I have made it so the JWKS spec is more closely followed. When the auth routine is called, the following happens:

1. Based on the `iss` variable which is set by the user, a request is made to to `<iss url>+.well-known/jwks.json`
2. If the response status code is 200 then the routine goes to the next step
3. It will parse the JSON contents of the `jwks.json` file which it previously fetched remotely 
4. Use the `jwk` library to parse the token
5. If the token is verified, then allow the user to use the API

**Comment by ozbillwang** [comment]
@shahzeb1 & @DavidWells 

Are you fine to accept a PR to use the environment in serverless, more than to update the iss server in `auth.js` directly?

Change in `serverless.yml`
```
custom:
  ISS: https://<url>.com/

  auth:
    handler: auth.authorize
    environment:
      ISS: ${self:custom.ISS}/
```

Change in `auth.js`
```
const iss = process.env.ISS;
```

Second, how to generate the `id_token`, what the `id_token` looks like? Can you share any details for me?

**Comment by shahzeb1** [comment]
@ozbillwang:
> Are you fine to accept a PR to use the environment in serverless.yml, more than to update the iss server in auth.js directly?

Sure I see no problem with that, but I assume anyone who is diving into this serverless code could modify the example to their needs. If things in the config are reliant on environment variables, then the README would have to account for that. Just seems like an unnecessary step.

> Second, how to generate the Cognito id_token, what the id_token looks like? Can you share any details for me?

Sure thing. So an `id_token` follows a very specific spec ([found here](https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.4)) but it's essentially just a JSON object with a few properties. [Auth0](https://auth0.com/docs/tokens/id-token#id-token-payload) has a good breakdown of what `id_token` contains, and if you're using AWS Cognito, you can refer to this [AWS docs page](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html). In my specific use case, I integrated Auth0 as a provider for AWS Cognito ([guide here](https://auth0.com/docs/integrations/integrating-auth0-amazon-cognito-mobile-apps)). This allows me to do user management with Auth0, but still get IAM resource control via AWS Cognito. 

> Third, how to automatically generate the id_token when access api gateway. Do you mean from cognito UI?

So I assume by "automatically generate the id_token when access api gateway" you mean automatically generate it for an anonymous (not yet logged in) user. The [Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html) do a good job of walking through what an authentication flow looks like with these auth tokens.

**Comment by ozbillwang** [comment]
@shahzeb1 

Thanks a lot. I have gone through some of the documents you mentioned, seems I need re-read them again.

Regarding the id token, I made a test case to generate [cognito three tokens](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html)  with this repo: https://github.com/serverless-projects/serverless-authorizers/tree/master/cognito/Cognito_issues_three_tokens

Its output is `base64`

    $ npm install; node test.js

    userData: {"Username":"bill","Pool":{"userPoolId":"....
    ===========================
    ID Token: eyJraWQiOiJoTxxxxVtZm1K5wZmIFA
    ===========================
    Access token: eyJraWQiOixxxxy5H5LaCQTw
    ===========================
    Refresh token: eyJjdHkiOixxxx8twwVe2CnDKMig

But when I feed to curl command with header, always failed with message: **Unauthorized**

    curl --header "Authorization: bearer <id_token>" https://{api}.execute-api.{region}.amazonaws.com/api/private

Do you know what type of bearer id token I need feed to?  If it is not `Base64`, then what format I should export it.  How it looks like?

**Comment by shahzeb1** [comment]
@ozbillwang

OK, so the first thing I would do is paste in that ID token into [JWT.io](https://jwt.io/). Does everything look right?

I would check cloud watch logs to see if there is an error specific to that function. I would also use the API Gateway AWS test endpoint method of testing the private endpoint. It is also important to remember that AWS Cognito and AWS Cognito federated identities are two separate things (I know, it starts getting real confusing). Here's an [official guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html) on using user pools with an API endpoint.

Since the [auth.js](auth.js) file is pretty easy to follow, I would reccomend adding some console.log statements to see which condition your token isn't passing on.

**Pull request merged**
